### ISSUE TITLE
Add option to w_assign to calculate assignments based on first and last time points

### ISSUE THREAD

**Issue by synapticarbors** [westpa/west_tools#5]
This feature request would simplify the user experience for using the postanalysis reweighting tools. In order for the analysis to be valid, assignments must be calculated using only the first and last time points in a trajectory segment as opposed to the current mode that uses all points. It would be nice to have an optional flag to use just the first and last time points. Currently the user has to manually down-sample their west.h5 file before running `w_assign`.

**Comment by ajoshpratt** [comment]
I'm currently making modifications to the assignment routines in the branch ed_kinetics in order to ensure correct event durations are calculated.  While I'm hesitant to add an extra feature on to a branch that isn't specifically designed for it, it would make sense (and certainly, make my life easier) if I went ahead and made the changes there, so long as no one minds approving and merging changes for both a fix and a feature change.  Otherwise, I'll have to manually merge any conflicts.

I actually think we give options to subsample fractions of tau, up to the entire tau; there's some evidence that suggests there are situations where we might want to play with the subsampling options, and building in code that allows for that would be a good idea, I think.

Adam

**Comment by synapticarbors** [comment]
I'm fine with both making the changes in the established event duration branch as well as providing a more flexible subsampling option in `w_assign`.

**Comment by ajoshpratt** [comment]
This feature has been added in to w_assign in the DEVELOPMENT branch of west_tools.  Seems to be working.
